version: '3.7'

services:
  app-server:
    build:
      context: mlhj-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - frontend

  app-client:
    build:
      context: mlhj-frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:8080/mlhj/journey
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend 

networks:
  frontend:   